In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:

from sklearn.impute import SimpleImputer

In [42]:
from sklearn.preprocessing import OneHotEncoder

In [41]:
from sklearn.preprocessing import OrdinalEncoder

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x = df.drop('has_covid',axis=1)

In [15]:
y = df['has_covid']

In [16]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3,random_state=2)

In [12]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [18]:
si = SimpleImputer()

In [23]:
x_train_f = si.fit_transform(x_train[['fever']])
x_test_f = si.fit_transform(x_test[['fever']])

In [38]:
x_train_f

array([[102.     ],
       [100.     ],
       [ 98.     ],
       [ 99.     ],
       [101.     ],
       [100.     ],
       [101.     ],
       [103.     ],
       [100.78125],
       [100.78125],
       [ 99.     ],
       [ 98.     ],
       [101.     ],
       [ 99.     ],
       [104.     ],
       [101.     ],
       [100.78125],
       [100.     ],
       [102.     ],
       [101.     ],
       [101.     ],
       [101.     ],
       [ 98.     ],
       [104.     ],
       [ 99.     ],
       [100.78125],
       [104.     ],
       [ 99.     ],
       [101.     ],
       [100.     ],
       [104.     ],
       [100.78125],
       [ 99.     ],
       [ 98.     ],
       [104.     ],
       [ 99.     ],
       [101.     ],
       [100.     ],
       [104.     ],
       [100.     ],
       [101.     ],
       [101.     ],
       [104.     ],
       [103.     ],
       [ 99.     ],
       [ 98.     ],
       [ 98.     ],
       [101.     ],
       [100.     ],
       [100.     ],


In [25]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [34]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [35]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])

In [36]:
#x_train_oe = oe.fit_transform(x_train[['cough']])
x_train_cough = oe.fit_transform(x_train[['cough']])

In [37]:
x_test_cough = oe.fit_transform(x_test[['cough']])

In [39]:
x_train_cough

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.]])

In [51]:
from sklearn.preprocessing import OneHotEncoder

In [54]:
#ohe = OneHoteEncoder(drop='first')
ohe = OneHotEncoder(drop='first')

In [49]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [57]:
x_train_ohe = ohe.fit_transform(x_train[['gender','city']]).toarray()

In [58]:
x_train_ohe

array([[0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],


In [74]:
from sklearn.compose import ColumnTransformer


In [75]:
transformer = ColumnTransformer(transformers=
                                [('so1',SimpleImputer(),['fever']),
                                 ('so2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                 ('so3'),OneHotEncoder(drop='first'),['gender','city']],
                                remainder='passthrough')

In [77]:

transformer.fit_transform(x_train).shape

TypeError: 'OneHotEncoder' object is not iterable

In [79]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

In [86]:
transformer.fit_transform(x_train)

array([[102.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         69.     ],
       [100.     ,   0.     ,   1.     ,   1.     ,   0.     ,   0.     ,
         27.     ],
       [ 98.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         64.     ],
       [ 99.     ,   1.     ,   1.     ,   0.     ,   0.     ,   0.     ,
         66.     ],
       [101.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         38.     ],
       [100.     ,   0.     ,   1.     ,   0.     ,   0.     ,   0.     ,
         11.     ],
       [101.     ,   1.     ,   1.     ,   0.     ,   0.     ,   0.     ,
         14.     ],
       [103.     ,   1.     ,   1.     ,   0.     ,   0.     ,   0.     ,
         46.     ],
       [100.78125,   0.     ,   1.     ,   1.     ,   0.     ,   0.     ,
         38.     ],
       [100.78125,   0.     ,   0.     ,   1.     ,   0.     ,   0.     ,
         75.     ],
       [ 99.     ,   1.     ,   0.     ,   0.     ,   1.    